In [1]:
from datetime import date, timedelta
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, LSTM
from tensorflow.keras import callbacks
from tensorflow.keras.callbacks import ModelCheckpoint

In [2]:
df_train = pd.read_csv('train.csv', usecols=[1, 2, 3, 4, 5], dayfirst=True,
    dtype={'onpromotion': bool},
    converters={'unit_sales': lambda u: np.log1p(float(u)) if float(u) > 0 else 0},
    parse_dates=["date"],
)

In [3]:
df_train

              date  store_nbr  item_nbr  unit_sales  onpromotion
0       2017-08-16         25    103665    2.079442        False
1       2017-08-16         25    105574    0.693147        False
2       2017-08-16         25    105575    1.098612        False
3       2017-08-16         25    108079    0.693147        False
4       2017-08-16         25    108701    0.693147        False
...            ...        ...       ...         ...          ...
1048570 2017-08-20         48    956013    3.465736        False
1048571 2017-08-20         48    956014    4.060443        False
1048572 2017-08-20         48    957096    1.945910        False
1048573 2017-08-20         48    957098    1.609438        False
1048574 2017-08-20         48    958514    1.945910        False

[1048575 rows x 5 columns]

In [4]:
df_test = pd.read_csv("test.csv", usecols=[0, 1, 2, 3, 4], dayfirst=True,
#     dtype={'onpromotion': bool},
    parse_dates=["date"]
).set_index(
    ['store_nbr', 'item_nbr', 'date']
)

In [5]:
df_test

                                      id  unit_sales
store_nbr item_nbr date
1         96995    2017-08-16  125497040         7.0
          99197    2017-08-16  125497041         1.0
          103501   2017-08-16  125497042         2.0
          103520   2017-08-16  125497043         1.0
          103665   2017-08-16  125497044         1.0
...                                  ...         ...
53        1955347  2017-08-20  126545610        31.0
          1956004  2017-08-20  126545611        57.0
          1956062  2017-08-20  126545612         6.0
          1956354  2017-08-20  126545613         4.0
          1956479  2017-08-20  126545614         6.0

[1048575 rows x 2 columns]

In [269]:
items = pd.read_csv("items.csv",).set_index("item_nbr")
items

                    family  class  perishable
item_nbr
96995            GROCERY I   1093           0
99197            GROCERY I   1067           0
103501            CLEANING   3008           0
103520           GROCERY I   1028           0
103665        BREAD/BAKERY   2712           1
...                    ...    ...         ...
2132318          GROCERY I   1002           0
2132945          GROCERY I   1026           0
2132957          GROCERY I   1068           0
2134058          BEVERAGES   1124           0
2134244   LIQUOR,WINE,BEER   1364           0

[4100 rows x 3 columns]

In [6]:
df_2017 = df_train.loc[df_train.date>=pd.Timestamp(2017,8,16)]
#del df_train
df_2017

              date  store_nbr  item_nbr  unit_sales  onpromotion
0       2017-08-16         25    103665    2.079442        False
1       2017-08-16         25    105574    0.693147        False
2       2017-08-16         25    105575    1.098612        False
3       2017-08-16         25    108079    0.693147        False
4       2017-08-16         25    108701    0.693147        False
...            ...        ...       ...         ...          ...
1048570 2017-08-20         48    956013    3.465736        False
1048571 2017-08-20         48    956014    4.060443        False
1048572 2017-08-20         48    957096    1.945910        False
1048573 2017-08-20         48    957098    1.609438        False
1048574 2017-08-20         48    958514    1.945910        False

[1048575 rows x 5 columns]

In [8]:
# Identify and remove duplicate index entries
df_2017 = df_2017[~df_2017.index.duplicated(keep='first')]

promo_2017_train = df_2017.set_index(["store_nbr", "item_nbr", "date"])[["onpromotion"]].unstack(level=-1).fillna(False)

promo_2017_train.columns = promo_2017_train.columns.get_level_values(1) 

promo_2017_test = df_test[["onpromotion"]].unstack(level=-1).fillna(False)

promo_2017_test.columns = promo_2017_test.columns.get_level_values(1)

promo_2017_test = promo_2017_test.reindex(promo_2017_train.index).fillna(False)

promo_2017 = pd.concat([promo_2017_train, promo_2017_test], axis=1)

del promo_2017_test, promo_2017_train

ValueError: Index contains duplicate entries, cannot reshape

In [232]:
df_2017 = df_2017.set_index(
    ["store_nbr", "item_nbr", "date"])[["unit_sales"]].unstack(
        level=-1).fillna(0)
df_2017.columns = df_2017.columns.get_level_values(1)

In [233]:
items = items.reindex(df_2017.index.get_level_values(1))

def get_timespan(df, dt, minus, periods, freq='D'):
    return df[pd.date_range(dt - timedelta(days=minus), periods=periods, freq=freq)]

In [234]:
def prepare_dataset(t2017, is_train=True):
    X = pd.DataFrame({
        "day_1_2017": get_timespan(df_2017, t2017, 1, 1).values.ravel(),
        "mean_3_2017": get_timespan(df_2017, t2017, 3, 3).mean(axis=1).values,
        "mean_7_2017": get_timespan(df_2017, t2017, 7, 7).mean(axis=1).values,
        "mean_14_2017": get_timespan(df_2017, t2017, 14, 14).mean(axis=1).values,
        "mean_30_2017": get_timespan(df_2017, t2017, 30, 30).mean(axis=1).values,
        "mean_60_2017": get_timespan(df_2017, t2017, 60, 60).mean(axis=1).values,
        "mean_140_2017": get_timespan(df_2017, t2017, 140, 140).mean(axis=1).values,
        "promo_14_2017": get_timespan(promo_2017, t2017, 14, 14).sum(axis=1).values,
        "promo_60_2017": get_timespan(promo_2017, t2017, 60, 60).sum(axis=1).values,
        "promo_140_2017": get_timespan(promo_2017, t2017, 140, 140).sum(axis=1).values
    })
    for i in range(7):
        X['mean_4_dow{}_2017'.format(i)] = get_timespan(df_2017, t2017, 28-i, 4, freq='7D').mean(axis=1).values
        X['mean_20_dow{}_2017'.format(i)] = get_timespan(df_2017, t2017, 140-i, 20, freq='7D').mean(axis=1).values
    for i in range(16):
        X["promo_{}".format(i)] = promo_2017[
            t2017 + timedelta(days=i)].values.astype(np.uint8)
    if is_train:
        y = df_2017[
            pd.date_range(t2017, periods=16)
        ].values
        return X, y
    return X

In [235]:
print("Preparing dataset...")
t2017 = date(2017, 8, 16)
X_l, y_l = [], []
for i in range(6):
    delta = timedelta(days=7 * i)
    X_tmp, y_tmp = prepare_dataset(
        t2017 + delta
    )
    X_l.append(X_tmp)
    y_l.append(y_tmp)

Preparing dataset...

KeyError: "None of [DatetimeIndex(['2017-08-14'], dtype='datetime64[ns]', freq='D')] are in the [columns]"

In [11]:
X_train = pd.concat(X_l, axis=0)
y_train = np.concatenate(y_l, axis=0)
del X_l, y_l
X_val, y_val = prepare_dataset(date(2017, 7, 26))
X_test = prepare_dataset(date(2017, 8, 16), is_train=False)

In [12]:
stores_items = pd.DataFrame(index=df_2017.index)
test_ids = df_test[['id']]

items = items.reindex( stores_items.index.get_level_values(1) )

In [13]:
X_train = X_train.as_matrix()
X_test = X_test.as_matrix()
X_val = X_val.as_matrix()
X_train = X_train.reshape((X_train.shape[0], 1, X_train.shape[1]))
X_test = X_test.reshape((X_test.shape[0], 1, X_test.shape[1]))
X_val = X_val.reshape((X_val.shape[0], 1, X_val.shape[1]))

In [14]:
model = Sequential()
model.add(LSTM(32, input_shape=(X_train.shape[1],X_train.shape[2])))
model.add(Dropout(.1))
model.add(Dense(32))
model.add(Dropout(.2))
model.add(Dense(1))
model.compile(loss = 'mse', optimizer='adam', metrics=['mse'])

In [15]:
N_EPOCHS = 5

val_pred = []
test_pred = []
# wtpath = 'weights.hdf5'  # To save best epoch. But need Keras bug to be fixed first.
sample_weights=np.array( pd.concat([items["perishable"]] * 6) * 0.25 + 1 )

In [16]:
for i in range(16):
    print("=" * 50)
    print("Step %d" % (i+1))
    print("=" * 50)
    y = y_train[:, i]
    xv = X_val
    yv = y_val[:, i]
    model.fit(X_train, y, batch_size = 512, epochs = N_EPOCHS, verbose=2,
               sample_weight=sample_weights, validation_data=(xv,yv) ) 
    val_pred.append(model.predict(X_val))
    test_pred.append(model.predict(X_test))

==================================================
Step 1
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 26s - loss: 0.3990 - mean_squared_error: 0.3760 - val_loss: 0.3116 - val_mean_squared_error: 0.3116
Epoch 2/5
 - 24s - loss: 0.3554 - mean_squared_error: 0.3363 - val_loss: 0.3021 - val_mean_squared_error: 0.3021
Epoch 3/5
 - 23s - loss: 0.3457 - mean_squared_error: 0.3275 - val_loss: 0.2972 - val_mean_squared_error: 0.2972
Epoch 4/5
 - 22s - loss: 0.3406 - mean_squared_error: 0.3228 - val_loss: 0.2982 - val_mean_squared_error: 0.2982
Epoch 5/5
 - 23s - loss: 0.3384 - mean_squared_error: 0.3209 - val_loss: 0.2987 - val_mean_squared_error: 0.2987
==================================================
Step 2
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 25s - loss: 0.3660 - mean_squared_error: 0.3452 - val_loss: 0.3426 - val_mean_squared_error: 0.3426
Epoch 2/5
 - 24s - loss: 0.3619 - mean_squared_error: 0.3415 - val_loss: 0.3266 - val_mean_squared_error: 0.3266
Epoch 3/5
 - 23s - loss: 0.3615 - mean_squared_error: 0.3411 - val_loss: 0.3282 - val_mean_squared_error: 0.3282
Epoch 4/5
 - 20s - loss: 0.3604 - mean_squared_error: 0.3401 - val_loss: 0.3255 - val_mean_squared_error: 0.3255
Epoch 5/5
 - 20s - loss: 0.3601 - mean_squared_error: 0.3398 - val_loss: 0.3306 - val_mean_squared_error: 0.3306
==================================================
Step 3
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 20s - loss: 0.3706 - mean_squared_error: 0.3508 - val_loss: 0.3421 - val_mean_squared_error: 0.3421
Epoch 2/5
 - 20s - loss: 0.3647 - mean_squared_error: 0.3455 - val_loss: 0.3409 - val_mean_squared_error: 0.3409
Epoch 3/5
 - 21s - loss: 0.3637 - mean_squared_error: 0.3446 - val_loss: 0.3398 - val_mean_squared_error: 0.3398
Epoch 4/5
 - 22s - loss: 0.3629 - mean_squared_error: 0.3438 - val_loss: 0.3398 - val_mean_squared_error: 0.3398
Epoch 5/5
 - 23s - loss: 0.3626 - mean_squared_error: 0.3436 - val_loss: 0.3401 - val_mean_squared_error: 0.3401
==================================================
Step 4
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 21s - loss: 0.3991 - mean_squared_error: 0.3772 - val_loss: 0.3609 - val_mean_squared_error: 0.3609
Epoch 2/5
 - 21s - loss: 0.3915 - mean_squared_error: 0.3702 - val_loss: 0.3571 - val_mean_squared_error: 0.3571
Epoch 3/5
 - 21s - loss: 0.3903 - mean_squared_error: 0.3692 - val_loss: 0.3552 - val_mean_squared_error: 0.3552
Epoch 4/5
 - 21s - loss: 0.3897 - mean_squared_error: 0.3686 - val_loss: 0.3533 - val_mean_squared_error: 0.3533
Epoch 5/5
 - 21s - loss: 0.3887 - mean_squared_error: 0.3677 - val_loss: 0.3625 - val_mean_squared_error: 0.3625
==================================================
Step 5
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 21s - loss: 0.4105 - mean_squared_error: 0.3882 - val_loss: 0.3615 - val_mean_squared_error: 0.3615
Epoch 2/5
 - 21s - loss: 0.4024 - mean_squared_error: 0.3808 - val_loss: 0.3599 - val_mean_squared_error: 0.3599
Epoch 3/5
 - 21s - loss: 0.4012 - mean_squared_error: 0.3797 - val_loss: 0.3586 - val_mean_squared_error: 0.3586
Epoch 4/5
 - 21s - loss: 0.3999 - mean_squared_error: 0.3785 - val_loss: 0.3586 - val_mean_squared_error: 0.3586
Epoch 5/5
 - 21s - loss: 0.3997 - mean_squared_error: 0.3783 - val_loss: 0.3661 - val_mean_squared_error: 0.3661
==================================================
Step 6
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 21s - loss: 0.4004 - mean_squared_error: 0.3775 - val_loss: 0.3600 - val_mean_squared_error: 0.3600
Epoch 2/5
 - 22s - loss: 0.3930 - mean_squared_error: 0.3706 - val_loss: 0.3649 - val_mean_squared_error: 0.3649
Epoch 3/5
 - 22s - loss: 0.3914 - mean_squared_error: 0.3691 - val_loss: 0.3597 - val_mean_squared_error: 0.3597
Epoch 4/5
 - 23s - loss: 0.3908 - mean_squared_error: 0.3686 - val_loss: 0.3621 - val_mean_squared_error: 0.3621
Epoch 5/5
 - 22s - loss: 0.3901 - mean_squared_error: 0.3679 - val_loss: 0.3618 - val_mean_squared_error: 0.3618
==================================================
Step 7
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 21s - loss: 0.3866 - mean_squared_error: 0.3653 - val_loss: 0.4123 - val_mean_squared_error: 0.4123
Epoch 2/5
 - 22s - loss: 0.3811 - mean_squared_error: 0.3603 - val_loss: 0.4126 - val_mean_squared_error: 0.4126
Epoch 3/5
 - 22s - loss: 0.3803 - mean_squared_error: 0.3596 - val_loss: 0.4129 - val_mean_squared_error: 0.4129
Epoch 4/5
 - 21s - loss: 0.3796 - mean_squared_error: 0.3590 - val_loss: 0.4165 - val_mean_squared_error: 0.4165
Epoch 5/5
 - 21s - loss: 0.3792 - mean_squared_error: 0.3586 - val_loss: 0.4441 - val_mean_squared_error: 0.4441
==================================================
Step 8
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 22s - loss: 0.3746 - mean_squared_error: 0.3554 - val_loss: 0.4025 - val_mean_squared_error: 0.4025
Epoch 2/5
 - 22s - loss: 0.3676 - mean_squared_error: 0.3492 - val_loss: 0.3960 - val_mean_squared_error: 0.3960
Epoch 3/5
 - 22s - loss: 0.3662 - mean_squared_error: 0.3480 - val_loss: 0.4038 - val_mean_squared_error: 0.4038
Epoch 4/5
 - 23s - loss: 0.3657 - mean_squared_error: 0.3475 - val_loss: 0.4007 - val_mean_squared_error: 0.4007
Epoch 5/5
 - 22s - loss: 0.3649 - mean_squared_error: 0.3468 - val_loss: 0.4181 - val_mean_squared_error: 0.4181
==================================================
Step 9
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 21s - loss: 0.3815 - mean_squared_error: 0.3603 - val_loss: 0.3829 - val_mean_squared_error: 0.3829
Epoch 2/5
 - 796s - loss: 0.3757 - mean_squared_error: 0.3550 - val_loss: 0.3847 - val_mean_squared_error: 0.3847
Epoch 3/5
 - 15s - loss: 0.3747 - mean_squared_error: 0.3540 - val_loss: 0.3829 - val_mean_squared_error: 0.3829
Epoch 4/5
 - 13s - loss: 0.3740 - mean_squared_error: 0.3534 - val_loss: 0.3962 - val_mean_squared_error: 0.3962
Epoch 5/5
 - 12s - loss: 0.3736 - mean_squared_error: 0.3530 - val_loss: 0.3790 - val_mean_squared_error: 0.3790
==================================================
Step 10
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 13s - loss: 0.3880 - mean_squared_error: 0.3675 - val_loss: 0.3734 - val_mean_squared_error: 0.3734
Epoch 2/5
 - 14s - loss: 0.3805 - mean_squared_error: 0.3609 - val_loss: 0.3724 - val_mean_squared_error: 0.3724
Epoch 3/5
 - 18s - loss: 0.3790 - mean_squared_error: 0.3595 - val_loss: 0.3732 - val_mean_squared_error: 0.3732
Epoch 4/5
 - 20s - loss: 0.3782 - mean_squared_error: 0.3588 - val_loss: 0.3692 - val_mean_squared_error: 0.3692
Epoch 5/5
 - 20s - loss: 0.3777 - mean_squared_error: 0.3584 - val_loss: 0.3725 - val_mean_squared_error: 0.3725
==================================================
Step 11
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 19s - loss: 0.4209 - mean_squared_error: 0.3983 - val_loss: 0.3805 - val_mean_squared_error: 0.3805
Epoch 2/5
 - 13s - loss: 0.4123 - mean_squared_error: 0.3904 - val_loss: 0.3801 - val_mean_squared_error: 0.3801
Epoch 3/5
 - 15s - loss: 0.4109 - mean_squared_error: 0.3892 - val_loss: 0.3760 - val_mean_squared_error: 0.3760
Epoch 4/5
 - 13s - loss: 0.4099 - mean_squared_error: 0.3883 - val_loss: 0.3753 - val_mean_squared_error: 0.3753
Epoch 5/5
 - 12s - loss: 0.4096 - mean_squared_error: 0.3880 - val_loss: 0.3774 - val_mean_squared_error: 0.3774
==================================================
Step 12
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 13s - loss: 0.4327 - mean_squared_error: 0.4099 - val_loss: 0.3895 - val_mean_squared_error: 0.3895

Epoch 2/5
 - 13s - loss: 0.4239 - mean_squared_error: 0.4017 - val_loss: 0.3888 - val_mean_squared_error: 0.3888
Epoch 3/5
 - 17s - loss: 0.4219 - mean_squared_error: 0.3999 - val_loss: 0.3895 - val_mean_squared_error: 0.3895
Epoch 4/5
 - 16s - loss: 0.4202 - mean_squared_error: 0.3983 - val_loss: 0.3899 - val_mean_squared_error: 0.3899
Epoch 5/5
 - 17s - loss: 0.4200 - mean_squared_error: 0.3980 - val_loss: 0.3870 - val_mean_squared_error: 0.3870
==================================================
Step 13
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 17s - loss: 0.4149 - mean_squared_error: 0.3916 - val_loss: 0.3798 - val_mean_squared_error: 0.3798
Epoch 2/5
 - 15s - loss: 0.4067 - mean_squared_error: 0.3840 - val_loss: 0.3788 - val_mean_squared_error: 0.3788
Epoch 3/5
 - 15s - loss: 0.4055 - mean_squared_error: 0.3829 - val_loss: 0.3806 - val_mean_squared_error: 0.3806
Epoch 4/5
 - 16s - loss: 0.4046 - mean_squared_error: 0.3821 - val_loss: 0.3769 - val_mean_squared_error: 0.3769
Epoch 5/5
 - 16s - loss: 0.4039 - mean_squared_error: 0.3815 - val_loss: 0.3776 - val_mean_squared_error: 0.3776
==================================================
Step 14
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 17s - loss: 0.3999 - mean_squared_error: 0.3781 - val_loss: 0.3660 - val_mean_squared_error: 0.3660
Epoch 2/5
 - 16s - loss: 0.3939 - mean_squared_error: 0.3727 - val_loss: 0.3633 - val_mean_squared_error: 0.3633
Epoch 3/5
 - 15s - loss: 0.3929 - mean_squared_error: 0.3718 - val_loss: 0.3632 - val_mean_squared_error: 0.3632
Epoch 4/5
 - 16s - loss: 0.3924 - mean_squared_error: 0.3713 - val_loss: 0.3638 - val_mean_squared_error: 0.3638
Epoch 5/5
 - 16s - loss: 0.3916 - mean_squared_error: 0.3706 - val_loss: 0.3650 - val_mean_squared_error: 0.3650
==================================================
Step 15
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 16s - loss: 0.3891 - mean_squared_error: 0.3694 - val_loss: 0.3537 - val_mean_squared_error: 0.3537
Epoch 2/5
 - 18s - loss: 0.3813 - mean_squared_error: 0.3624 - val_loss: 0.3516 - val_mean_squared_error: 0.3516
Epoch 3/5
 - 18s - loss: 0.3801 - mean_squared_error: 0.3613 - val_loss: 0.3521 - val_mean_squared_error: 0.3521
Epoch 4/5
 - 18s - loss: 0.3794 - mean_squared_error: 0.3607 - val_loss: 0.3501 - val_mean_squared_error: 0.3501
Epoch 5/5
 - 18s - loss: 0.3789 - mean_squared_error: 0.3602 - val_loss: 0.3532 - val_mean_squared_error: 0.3532
==================================================
Step 16
==================================================
Train on 1005090 samples, validate on 167515 samples
Epoch 1/5
 - 17s - loss: 0.3970 - mean_squared_error: 0.3752 - val_loss: 0.3757 - val_mean_squared_error: 0.3757
Epoch 2/5
 - 19s - loss: 0.3907 - mean_squared_error: 0.3693 - val_loss: 0.3730 - val_mean_squared_error: 0.3730
Epoch 3/5
 - 19s - loss: 0.3896 - mean_squared_error: 0.3682 - val_loss: 0.3726 - val_mean_squared_error: 0.3726
Epoch 4/5
 - 17s - loss: 0.3893 - mean_squared_error: 0.3680 - val_loss: 0.3723 - val_mean_squared_error: 0.3723
Epoch 5/5
 - 18s - loss: 0.3891 - mean_squared_error: 0.3677 - val_loss: 0.3728 - val_mean_squared_error: 0.3728

In [17]:
n_public = 5 # Number of days in public test set
weights=pd.concat([items["perishable"]]) * 0.25 + 1
print("Unweighted validation mse: ", mean_squared_error(
    y_val, np.array(val_pred).squeeze(axis=2).transpose()) )
print("Full validation mse:       ", mean_squared_error(
    y_val, np.array(val_pred).squeeze(axis=2).transpose(), sample_weight=weights) )
print("'Public' validation mse:   ", mean_squared_error(
    y_val[:,:n_public], np.array(val_pred).squeeze(axis=2).transpose()[:,:n_public], 
    sample_weight=weights) )
print("'Private' validation mse:  ", mean_squared_error(
    y_val[:,n_public:], np.array(val_pred).squeeze(axis=2).transpose()[:,n_public:], 
    sample_weight=weights) )

Unweighted validation mse:  0.369163668494
Full validation mse:        0.368709261587
'Public' validation mse:    0.339996983697
'Private' validation mse:   0.381760296992

In [18]:
y_test = np.array(test_pred).squeeze(axis=2).transpose()
df_preds = pd.DataFrame(
    y_test, index=stores_items.index,
    columns=pd.date_range("2017-08-16", periods=16)
).stack().to_frame("unit_sales")
df_preds.index.set_names(["store_nbr", "item_nbr", "date"], inplace=True)

In [19]:
submission = test_ids.join(df_preds, how="left").fillna(0)
submission["unit_sales"] = np.clip(np.expm1(submission["unit_sales"]), 0, 1000)
submission.to_csv('lstm.csv', float_format='%.4f', index=None)